name: Deployment

on:
#  pull_request:
#    branches: [ main ]
#    types: [ closed ]

  push:
    branches: [ main ]

jobs:
  deploy-test:
    runs-on: [ self-hosted, linux, x64 ]

    environment:
      name: test
      url: http://sas-test:3080/SASStudio

    steps:
      - uses: actions/checkout@v4
      - name: deploy code
        run: |
          rsync -avh -e ssh code/ sas@sas94test:/srv/sas/code/ --delete-after 

      - uses: actions/checkout@v4
      - name: deploy config
        run: rsync -avh -e ssh config/test/ sas@sas94test:/srv/sas/config/ --delete-after

      - name: add deploy message
        run: |
          date '+%Y-%m-%d %H:%M:%S' > ./deploy.txt
          echo "${{ github.server_url }}/${{ github.repository }}/tree/${{github.sha}}" >> ./deploy.txt
          echo "${{ github.event.head_commit.message }}" >> deploy.txt
          rsync -avh -e ssh ./deploy.txt sas@sas94test:/srv/sas/deploy.txt

  deploy-prod:
    runs-on: [ self-hosted, linux, x64 ]

    needs: [ deploy-test ]

    environment:
      name: production
      url: http://sas-prod:4080/SASStudio

    steps:
      - uses: actions/checkout@v4
      - name: deploy code
        run: rsync -avh -e ssh code/ sas@sas94prod:/srv/sas/code/ --delete-after 

      - uses: actions/checkout@v4
      - name: deploy config
        run: rsync -avh -e ssh config/prod/ sas@sas94prod:/srv/sas/config/ --delete-after 
