name: Deployment

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: [self-hosted, linux, x64]

    environment:
      name: test
      url: http://sas-test:3080/SASStudio

    steps:
      - uses: actions/checkout@v3
      - name: deploy code
        run: rsync -avh -e ssh code/ sas@sas94test:/srv/sas/ --delete-after 

  deploy-prod:
    runs-on: [self-hosted, linux, x64]

    needs: [ deploy-test ]

    environment:
      name: production
      url: http://sas-prod:4080/SASStudio

    steps:
      - uses: actions/checkout@v3
      - name: deploy code
        run: rsync -avh -e ssh code/ sas@sas94prod:/srv/sas/ --delete-after 
